In [108]:
import numpy as np
import pandas as pd

In [109]:
df = pd.read_csv('./dataset/dataset_csv.csv') #read the dataset
df.head()

AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [110]:
total_X = df.iloc[:, :-1].values #total_X is a matrix the size of 9568 X 4
total_y = df.iloc[:, -1].values  #total_Y is a vector the size of 9568

In [111]:
b = np.ones((total_X.shape[0],total_X.shape[1]+1)) # b is a 9568 X 5 matrix filled with ones.
b[:, 1:] = total_X #b is the total_X matrix except with first column filled with ones
total_X = b #reassign
print(total_X[:5])

[[1.00000e+00 8.34000e+00 4.07700e+01 1.01084e+03 9.00100e+01]
 [1.00000e+00 2.36400e+01 5.84900e+01 1.01140e+03 7.42000e+01]
 [1.00000e+00 2.97400e+01 5.69000e+01 1.00715e+03 4.19100e+01]
 [1.00000e+00 1.90700e+01 4.96900e+01 1.00722e+03 7.67900e+01]
 [1.00000e+00 1.18000e+01 4.06600e+01 1.01713e+03 9.72000e+01]]


In [112]:
#in order for us to verify the accuracy later, we will reserve about 20% of the whole dataset.
test_training_ratio       = 0.2
num_of_testing_example    = int(test_training_ratio*total_X.shape[0]) # (20/100) * 9568 = 1913.6. After flooring, 1913
num_of_training_example   = total_X.shape[0] - num_of_testing_example # 9568 - 1913 = 7655
X                         = total_X[:num_of_training_example] #matrix of size 7655 X 4. input X (according to the pdf note)
y                         = total_y[:num_of_training_example] #vector of size 7655. input y (according to the pdf note)
X_test                    = total_X[num_of_training_example:] #matrix of size 1913 X 4
y_test                    = total_y[num_of_training_example:] #vector of size 1913

In [113]:
X_transpose        = np.transpose(X) #matrix of size 4 X 7655
X_tranpose_times_X = X_transpose.dot(X)  #matrix of size 4 X 4

In [114]:
try:
    X_transpose_times_X_inverse                  = np.linalg.inv(X_tranpose_times_X) #matrix of size 4 X 4
    X_transpose_times_X_inverse_times_X_tranpose = X_transpose_times_X_inverse.dot(X_transpose) #matrix of size 4 X 7655
    theta                                        = X_transpose_times_X_inverse_times_X_tranpose.dot(y) #vector of size 4
except Exception as e:
    if str(e) == 'Singular matrix': #NOTE that inverse does not exist for singular matrices. i.e. determinant of the matrix is 0.
        #the system has to be solved manually if X_tranpose_times_X is a singular matrix
        theta = np.linalg.solve(X_tranpose_times_X, y) #solve the linear system of X tranpose * X = y

In [115]:
y_hat_test = X_test.dot(theta) #calculate h(x)
comparison = y_test - y_hat_test #compare h(x) with y
print(sum(comparison)) #total loss was only ~421.

421.099530803685


In [116]:
print(theta)

[ 4.57261604e+02 -1.97644295e+00 -2.33524675e-01  5.93789692e-02
 -1.58037984e-01]
